### ISSUE TITLE
Widget on page

### ISSUE THREAD

**Issue by Jogai** [adamosoftware/MvcProfiler#1]
Stuff like miniprofiler and glimpse use a widget that renders on the page for direct insight. I think this is really valuable because it provides a quick way to some valuable insights. Maybe its an idea to implement something like this in your project.

**Comment by adamosoftware** [comment]
Do you mean [this miniprofiler](https://miniprofiler.com)? Agree it's neat functionality, but I thought it was too complicated, and I wasn't really sure how to read what it was telling me. Also I don't know how to include MVC views in a nuget package. I know the Razor Class Library stuff will make it easier, but that's for .NET Core.

**Comment by Jogai** [comment]
Of course it would just list everything your profiler tracks. And I dont think its necessarry to use mvc for the widget. I'm not even sure those use it, it could be a bit of js.

**Comment by adamosoftware** [comment]
Not on roadmap now to implement page widget, but agree this would be ideal for a profiling solution. Thanks for mentioning Glimpse, I'd forgotten about that.
